const router = require('express').Router();
const c = require('../controllers/reservations.controller');
const { auth, authorizeStaff } = require('../middlewares/auth');
router.get('/', auth, authorizeStaff, c.getAll);
router.get('/queue', auth, authorizeStaff, c.getQueue);
router.post('/expire', auth, authorizeStaff, c.expireReservations);
router.get('/book/:bookId', auth, c.getBookQueue);
router.get('/:id', auth, c.getById);
router.post('/admin', auth, authorizeStaff, c.create);
router.post('/', auth, c.createHold);
router.put('/:id', auth, authorizeStaff, c.update);
router.patch('/:id/status', auth, authorizeStaff, c.updateStatus);
router.delete('/:id', auth, authorizeStaff, c.remove);
module.exports = router;
